apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-cloud-machineinfo
  namespace: ${Environment}
spec:
  selector:
    matchLabels:
      app: machineinfo
  replicas: 1
  template:
    metadata:
      labels:
        app: machineinfo      
    spec:
      containers:
      - name: machineinfo
        image: nehashirsat/helloworld:${Tag}
        ports:
        - containerPort: 8080
